# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftVersion=1.20.1
yarnMappings=1.20.1+build.10
loaderVersion=0.15.11
modID=hexthingy
fabricLanguageKotlinVersion=1.9.5+kotlin.1.8.22

# Mod Properties
modVersion=1.0.2
mavenGroup=me.uwutaku.hexthingy
archivesBaseName=hexthingy

# Dependencies
fabricVersion=0.92.2+1.20.1

# hex stuff
hexcastingVersion =0.11.1-7-pre-636
paucalVersion =0.6.0-pre-118
patchouliVersion=84

cardinalComponentsVersion=5.2.1
serializationHooksVersion=0.4.99999
clothConfigVersion=11.1.106
originsVersion=1.10.0
calioVersion=1.11.0